### PR TITLE
JessicaH- Add day number on CommonsOverview

### PR DESCRIPTION
**Pull request by jessicahsy**
This includes the code from my last PR for font change that has not been merged yet. Review only **CommonsOverview.js** and **dayUtils.js**

In this PR, I added a utility to calculate the number of days since the starting day. Previously, the commons.day is empty. The new function is called and assigned to this variable so that it displays the right day number in CommonsOverview. May be adding test cases and error messages for starting dates set the future, or maybe change so that admin cannot create a starting date beyond the current date.

# Storybook

* [Before](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-4/storybook/?path=/story/components-commons-commonsoverview--uncontrolled)
* [After](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-4/prs/15/storybook/?path=/story/components-commons-commonsoverview--uncontrolled)

# Screenshots
Before:
Screen Shot 2023-06-01 at 3 05 09 PM

After:
Screen Shot 2023-06-01 at 3 05 40 PM

### CODE REVIEW

**Comment by jessicahsy** [comment]
In this PR, I added tests for calcualteDays and moved this function into dateUtils. An extra parameter, currentDate, is passed in to the function so that it can be tested with mock current dates.

**Review by ykeung — COMMENTED** [review]
Might want to make the PR title clearer. 

In `CommonsOverview.js`, I'm not sure if `commons.day = calculateDays(commons.startingDate,today);` is good practice since the Commons model doesn't have a `day` variable.

**Review by ykeung — DISMISSED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM... will test on staff-qa

**Review by pconrad — CHANGES_REQUESTED** [review]
Looks like there are some failing tests after rebasing this on main

**Review by kshitij0407 — APPROVED** [review]
Looks good to me, I see the changes of moving day0 to day1

**Pull request merged**
