### PR TITLE
JacobW Sell Multiple Cows Backend

### PR DESCRIPTION
**Pull request by JacobWoodward2000**
Added logic and tests to allow selling groups of cows at a time, and a minor change in frontend to maintain functionality

### CODE REVIEW

**Review by ashleybudman — APPROVED** [review]
LGTM - no commented out code and passed all tests locally. Smaller PRs helped too!

**Review by pconrad — APPROVED** [review]
LGTM... will test on QA

**Review by pconrad — CHANGES_REQUESTED** [review]
I tried this on QA.   It seems to work, but there are a few concerns:
It works, but it "looks and feels" buggy because the frontend doesn't seem to have been updated to match.   A quick PR to do two things might help:


Update the display of cow price and current wealth to look like currency: $ and rounde to two  decimal places.
Not this:

image


But Market Cow Price `$102.40` and total wealth `$8072.50`

**Review by pconrad — CHANGES_REQUESTED** [review]
The other change is to make the cow price update immediately in the UI when it changes.  This has to do with managing and refreshing state in a React component; it might mean that the mutation that does buy or sell needs to invalidate the state key for the useBackend call that gets information from the Commons object.

**Comment by JacobWoodward2000** [comment]
I'm not sure what you mean when asking about making the cow price update. In the backend, this PR doesn't change the cow price, and the frontend only has a one line change to pass in the newly needed parameter.

**Review by pconrad — DISMISSED** [review]
LGTM

**Pull request merged**
