### PR TITLE
Yuki -  Updated UserCommonsController for total cows bought and sold

### PR DESCRIPTION
**Pull request by ykeung**
In this PR, I updated the UserCommonsController and CommonsController to add logic for total cows bought and sold. When a user buys/sells cows, total cows bought/sold increments by the same amount. Branched off of PR #50.

### CODE REVIEW

**Review by JacobWoodward2000 — DISMISSED** [review]
Looks good to me

**Review by pconrad — APPROVED** [review]
LGTM---will test on staff-qa

**Review by pconrad — DISMISSED** [review]
LGTM.. will test on staff-qa

**Comment by ykeung** [comment]
Maybe wait for #56 to be merged to main before merging this? I fixed a merge conflict due to buys backend changing, but not for sells backend yet since that PR hasn't been merged yet.

**Pull request merged**
