### PR TITLE
Yuki - Add total cows bought and sold to leaderboard table

### PR DESCRIPTION
**Pull request by ykeung**
In this PR, total cows bought and sold is visible on the leaderboard table.  Branched off #51.

# Storybook

Before
* [LeaderboardTable](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-4/storybook/?path=/story/components-leaderboard-leaderboardtable--five-user-commons)

After
* [LeaderboardTable](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-4/prs/74/storybook/?path=/story/components-leaderboard-leaderboardtable--five-user-commons)

# Screenshots

Before
image

After
image

### CODE REVIEW

**Review by kshitij0407 — DISMISSED** [review]
Looks good to me, code is working when I test it and it accurately keeps track of total cows bought and sold

**Review by kshitij0407 — DISMISSED** [review]
Looks good to me pt. 2

**Review by kshitij0407 — APPROVED** [review]
Looks good to me pt. 2

**Review by kshitij0407 — APPROVED** [review]
Looks good to me pt. 2

**Review by kshitij0407 — DISMISSED** [review]
lgtm

**Review by jessicahsy — DISMISSED** [review]

**Review by jessicahsy — APPROVED** [review]

**Pull request closed without merging**
