### PR TITLE
JacobW Scale Cow Sale Price Backend

### PR DESCRIPTION
**Pull request by JacobWoodward2000**
This PR added a boolean in Commons that determines if the profits from selling cows will decrease when they have less than 100 health, as well as the logic and tests necessary to make this functional in the backend.

This PR was branched off JacobW-SellMultipleCowsBackend due to them both being primarily located in the function that sells a user's cows.

### CODE REVIEW

**Review by ykeung — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM - will test on staff qa

**Comment by pconrad** [comment]
This one is on hold until after the concerns with #56 are handled.

**Review by pconrad — APPROVED** [review]
LGTM - will test on staff-qa

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
